# Generated by Django 2.2 on 2019-04-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('IT', 'Information and Technology'), ('Food', 'Restaurants, coffees and bars'), ('Bank', 'Banks and financial institutions'), ('Auto', 'Cars and accessories'), ('Service', 'Services'), ('Other', 'Other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('1', 'Very bad'), ('2', 'Bad'), ('3', 'Fair'), ('4', 'Good'), ('5', 'Very good')], max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('reviewer', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business_rating.Business')),
            ],
        ),
    ]
