# Generated by Django 2.2 on 2019-04-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_rating', '0003_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'Information and Technology'), ('Food', 'Restaurants, coffees and bars'), ('Bank', 'Banks and financial institutions'), ('Auto', 'Cars and accessories'), ('Service', 'Services'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
